#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <lucide-version>" >&2
  echo "Example: $0 0.29.0" >&2
  exit 2
fi

version="$1"
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
asset_dir="$repo_root/src/main/resources/assets/anarchyclient/font"
tmp_dir="$(mktemp -d)"

cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

zip_file="$tmp_dir/lucide-font-$version.zip"
download_url="https://github.com/lucide-icons/lucide/releases/download/v$version/lucide-font-$version.zip"

mkdir -p "$asset_dir"
curl --fail --location --show-error --silent "$download_url" --output "$zip_file"
unzip -q "$zip_file" -d "$tmp_dir"

font_root="$tmp_dir/lucide-font"
css_file="$font_root/lucide.css"
ttf_file="$font_root/lucide.ttf"

if [[ ! -f "$css_file" || ! -f "$ttf_file" ]]; then
  echo "Lucide font archive did not contain lucide.css and lucide.ttf" >&2
  exit 1
fi

cp "$ttf_file" "$asset_dir/lucide.ttf"

cat > "$asset_dir/lucide.json" <<'JSON'
{
  "providers": [
    {
      "type": "ttf",
      "file": "anarchyclient:lucide.ttf",
      "size": 14,
      "oversample": 4,
      "shift": [0, 0]
    }
  ]
}
JSON

{
  printf "# Generated by scripts/update-lucide-font.sh %s\n" "$version"
  printf "# Source: %s\n" "$download_url"
  awk '
    match($0, /^\.icon-([a-z0-9-]+):before \{ content: "\\([0-9a-fA-F]+)"; \}$/, parts) {
      print parts[1] "=" tolower(parts[2])
    }
  ' "$css_file"
} > "$asset_dir/lucide-icons.properties"

echo "Updated Lucide font assets for v$version"
